### ISSUE TITLE
HTM tasks, capabilities - What you can do

### ISSUE THREAD

**Issue by breznak** [htm-community/htm.core#683]
Review of encoders' coverage of sensory modalities https://github.com/htm-community/htm.core/issues/259 
Here we look at possibilities of HTM networks: 

### Tasks: 

- [x] prediction
  - [ ] multi-step ahead prediction: 
    - TODO: instead of current "for N-steps ahead prediction, look at N-1-th classifier in predictor and feed it TM(time)", instead do N steps of TM(time+1).predict. Then classify the TM(TM(time+N-i+1)). 
- [x] classification: MNIST #242 
  - [ ] advanced vision tasks
- [x] anomaly detection AD, see #205 
- [ ] (sub) sequence classification - important TODO (using CP, etc...) 
- [ ] multi-sensory integration - ie by Thalamus #676 
- [ ] sensory-motor integration, ie #672

**Comment by breznak** [comment]
FYI @ctrl-z-9000-times @fcr if you find other category or have more details, I'd like to keep collecting the info here.

**Comment by Finnfj** [comment]
Hello,
Just wanted to ask what became of experiments with

> TODO: instead of current "for N-steps ahead prediction, look at N-1-th classifier in predictor and feed it TM(time)", instead do N steps of TM(time+1).predict. Then classify the TM(TM(time+N-i+1)).

I'm currently using prediction the first time with HTM and thought that the predictor would have to work as you described it, based on the way it is used.
I am not too familiar with classification too, but I imagine this proposed method could maybe improve prediction?
